name: freetype_dart
version: 1.0.1
description: freetype dart bindings
homepage: https://github.com/insinfo/freetype_dart
repository: https://github.com/insinfo/freetype_dart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.9.0  
  ffi: ^2.1.0  
  image: ^4.1.4

dev_dependencies:
  ffigen: ^11.0.0
  

# ffigen:
  # output: 'lib/src/generated_bindings.dart'
  # name: 'FreetypeBinding'
  # description: 'Freetype binding for dart'
  # llvm-path:  
  #   - 'C:\llvm'
  # headers:
  #   entry-points:   
  #     - 'freetype/include/ft2build.h'         
  #     - 'freetype/include/freetype/freetype.h' 
  #   include-directives:
  #     - 'freetype/include/**'
  #     - 'freetype/include/freetype/**'
  #     - 'freetype/include/ft2build.h'
  #     - 'freetype/include/freetype/fterrdef.h'  
  #     - 'freetype/include/freetype/fterrors.h' 
  #     - 'freetype/include/freetype/ftimage.h' 
  #     - 'freetype/include/freetype/fttypes.h'  

  # compiler-opts:
  #   - '-Ifreetype/include/'  

