name: freetype_dart

environment:
  sdk: '>=3.0.0 < 4.0.0'

dependencies:
  ffi: any
  ffigen: any
  image: ^4.1.4

dev_dependencies:


ffigen:
  llvm-path:  
  - 'C:\llvm'
  output: 'lib/src/generated_bindings_beta.dart'
  headers:
    entry-points:
      #- 'C:\MyProjectsDart\freetype\freetype\include\merged.h'    
      #https://chromium.googlesource.com/chromium/src/third_party/freetype2/+/VER-2-BETA2
      - 'C:\MyProjectsDart\freetype\include_ver_2_beta_2\freetype.h'   